restroapp/urls.py
from django.urls import path, include
from .views import *
from restroapp import views


from django.contrib.auth import views as auth_views

app_name = 'restroapp'
urlpatterns = [



#client url
path('',ClientHomeView.as_view(), name = "clienthome"),



#about
path('about/<int:pk>/', AboutDetailView.as_view(), name = 'aboutdetail'),
path('about/<int:pk>/', SubAboutDetailView.as_view(), name = 'subabout'),


#message
path('contact/', MessageCreateView.as_view(), name = 'messagecreate'),


#contact
path('contact/', ContactListView.as_view(), name = 'contactlist'),


#team
path('about/<int:pk>/', TeamListView.as_view(), name = 'teamlist'),

#reason_to_choose
path('about/<int:pk>/', ReasonToChooseListView.as_view(), name = 'reason_to_choose'),

#client_voice
path('', ClientVoiceListView.as_view(), name = 'clientvoice'),


#order
path('order/', OrderCreateView.as_view(), name = 'order'),


#our_special
path('', OurSpecialListView.as_view(), name = 'ourspecial'),

#banner
path('', BannerDetailView.as_view(), name = 'bannerdetail'),


#gallery
path('gallery/list/', GalleryListView.as_view(), name = 'gallerylist'),
#food menu
path('menu/', Food_MenuListView.as_view(), name = 'menulist'),

#category
path('menu/', FoodCategory_ListView.as_view(), name = 'foodcategory'),



#login/logout
path('admin-login/',LoginView.as_view(),name="login"),
path('logout/', LogoutView.as_view(), name = 'logout'),



#admin urls start here

path('admin/home/', AdminHomeView.as_view(), name = 'adminhome'),

#Admin Profile
path('admin/profile/detail', AdminProfileDetailView.as_view(), name = 'adminprofiledetail'),


#contact 
path('admin/contact/', A_ContectListView.as_view(), name = 'a_contactlist'),
path('admin/contact/create/', A_ContactCreateView.as_view(), name = 'a_contactcreate'),
path('admin/contact/<int:pk>/update/', AdminContactUpdateView.as_view(), name = 'contactupdate'),


#message
path('message/list/', MessageListView.as_view(), name = 'messagelist'),
path('message/<int:pk>/delete/', MessageDeleteView.as_view(), name = 'messagedelete'),
path('message/<int:pk>/detail/', MessageDetailView.as_view(), name = 'messagedetailview'),



#About
path('admin/about/list/', A_AboutListView.as_view(), name = 'a_aboutlist'),
path('about/<int:pk>/update/', AboutUpdateView.as_view(), name = 'aboutupdateview'),
path('admin/subabout/list/', A_SubAboutListView.as_view(), name = 'a_subaboutlist'),
path('subabout/<int:pk>/update/', SubAboutUpdateView.as_view(), name = 'subaboutupdate'),

#team
path('admin/team/create/', A_TeamCreateView.as_view(), name = 'a_teamcreate'),
path('admin/team/list/', A_TeamListView.as_view(), name = 'a_teamlist'),
path('admin/team/<int:pk>/detail/', A_TeamDetailView.as_view(), name = 'a_teamdetail'),
path('admin/team/<int:pk>/delete/', A_TeamDeleteView.as_view(), name = 'a_teamdelete'),
path('admin/team/<int:pk>/update', A_TeamUpadateView.as_view(), name = 'a_teamupdate'),


#reason to choose us
path('admin/reason/create/', A_ReasonCreateView.as_view(), name = 'a_reasoncreate'),
path('admin/reason/list/', A_ReasonListView.as_view(), name = 'a_reasonlist'),
path('admin/reason/<int:pk>/detail/', A_ReasonDetailView.as_view(), name = 'a_reasondetail'),
path('admin/reason/<int:pk>/delete/', A_ReasonDeleteView.as_view(), name = 'a_reasondelete'),
path('admin/reason/<int:pk>/update/', A_ReasonUpdateView.as_view(), name = 'a_reasonupdate'),



#our special
path('admin/special/create/', A_SpecialCreateView.as_view(), name = 'a_specialcreate'),
path('admin/special/list/', A_SpecialListView.as_view(), name = 'a_speciallist'),
path('admin/special/<int:pk>/detail/', A_SpecialDetailView.as_view(), name = 'a_specialdetail'),
path('admin/special/<int:pk>/delete/', A_SpecialDeleteView.as_view(), name = 'a_specialdelete'),
path('admin/special/<int:pk>/update/', A_SpecialUpdateView.as_view(), name = 'a_specialupdate'),



#clientVoice urls
path('admin/voice/create/', A_VoiceCreateView.as_view(), name = 'a_clientvoicecreate'),
path('admin/voice/list/', A_VoiceListView.as_view(), name = 'a_clientvoicelist'),
path('admin/voice/<int:pk>/detail/', A_VoiceDetailView.as_view(), name = 'a_clientvoicedetail'),
path('admin/voice/<int:pk>/delete/', A_VoiceDeleteView.as_view(), name = 'a_clientvoicedelete'),
path('admin/voice/<int:pk>/update/', A_VoiceUpdateView.as_view(), name = 'a_clientvoiceupdate'), 



#online order urls
path('admin/order/list/', A_OrderListView.as_view(), name = 'a_orderlist'),
path('admin/order/<int:pk>/detail/', A_OrderDetailView.as_view(), name = 'a_orderdetail'),
path('admin/order/<int:pk>/delete/', A_OrderDeleteView.as_view(), name = 'a_orderdelete'),


#banner urls
path('admin/banner/list/', A_BannerListView.as_view(), name = 'a_bannerlist'),
path('admin/banner/<int:pk>/update/', A_BannerUpdateView.as_view(), name = 'a_bannerupdate'),


#gallery urls
path('admin/gallery/create/', A_GalleryCreateView.as_view(), name = 'a_gallerycreate'),
path('admin/gallery/list/', A_GalleryListView.as_view(), name = 'a_gallerylist'),
path('admin/gallery/<int:pk>/delete/', A_GalleryDeleteView.as_view(), name = 'a_gallerydelete'),
path('admin/gallery/<int:pk>/update/', A_GalleryUpdateView.as_view(), name = 'a_galleryupdate'),


#FoodCategory urls
path('admin/food-category/create/', FoodCategoryCreateView.as_view(), name = 'foodcategorycreate'),
path('admin/food-category/<int:pk>/delete/',FoodCategoryDeleteView.as_view(), name = 'foodcategorydelete'),
path('admin/food-category/list/', FoodCategoryListView.as_view(), name = 'foodcategorylist'),


#FoodMenu urls
path('admin/food-menu/create/', FoodMenuCreateView.as_view(), name = 'foodmenucreate'),
path('admin/food-menu/<int:pk>/update', FoodMenuUpdateView.as_view(), name = 'foodmenuupdate'),
path('admin/food-menu/list/', FoodMenuListView.as_view(), name = 'foodmenulist'),
path('admin/food-menu/<int:pk>/', FoodMenuDetailView.as_view(), name = 'foodmenudetail'),
path('admin/food-menu/<int:pk>/delete/', FoodMenuDeleteView.as_view(), name = 'foodmenudelete'),


#admin settings
path('admin/settings',A_SettingsView.as_view(), name = 'a_settings'),


#admin registration
path('admin/registration/',A_RegistrationView.as_view(), name = 'a_registration'),
path('activate/<uidb64>/<token>/',views.activate, name='activate'),

#username check
path('username-check/',UsernameCheckView.as_view(), name = 'username_check'),



#user authentication
path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(template_name='admintemplates/change-password.html',
        	success_url = '/change-password-done/'),
        name = 'password_change'
    ),
path(
		'change-password-done/',
		auth_views.PasswordChangeDoneView.as_view(
			template_name = 'admintemplates/password_change_done.html'),
		name = 'password_change_done' 
	),


path('password-reset/',auth_views.PasswordResetView.as_view(
    template_name = 'admintemplates/password_reset_form.html',
    subject_template_name='admintemplates/password_reset_subject.txt',
    email_template_name='admintemplates/password_reset_email.html',
    success_url = '/password_reset/done/'
 ), name = 'password_reset_form'),


path('password_reset/done/',
     auth_views.PasswordResetDoneView.as_view(
         template_name='admintemplates/password_reset_done.html'
     ),
     name='password_reset_done'),
path('password-reset-confirm/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(
         template_name='admintemplates/password_reset_confirm.html',
         success_url = '/reset/done/'
     ),
     name='password_reset_confirm'),
path('reset/done/',
     auth_views.PasswordResetCompleteView.as_view(
         template_name='admintemplates/password_reset_complete.html'
     ),
     name='password_reset_complete'),
]

restroproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include


from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('restroapp.urls')),
    path('',include("django.contrib.auth.urls"))
    

]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/clienttemplates/adminlogin.html
{% load static %}
<!DOCTYPE html>
<head>
<title>Restro|Admin-Login</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Visitors Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- bootstrap-css -->
<link rel="stylesheet" href="{% static 'adminstatic/css/bootstrap.min.css' %}" >
<!-- //bootstrap-css -->
<!-- Custom CSS -->
<link href="{% static 'adminstatic/css/style.css' %}" rel='stylesheet' type='text/css' />
<link href="{% static 'adminstatic/css/style-responsive.css' %}" rel="stylesheet"/>
<!-- font CSS -->
<link href='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
<!-- font-awesome icons -->
<link rel="stylesheet" href="{% static 'adminstatic/css/font.css' %}" type="text/css"/>
<link href="{% static 'adminstatic/css/font-awesome.css' %}" rel="stylesheet"> 
<!-- //font-awesome icons -->
<script src="{% static 'adminstatic/js/jquery2.0.3.min.js' %}"></script>
</head>
<body>
<div class="log-w3">
<div class="w3layouts-main">
	<h2>LogIn Now</h2>
	{% if error %}
		{{error}}
	{% endif %}
		<form method="post">
			{% csrf_token %}
			
			{{form.username}}
			
			{{form.password}}





			<h6><a href="{% url 'restroapp:password_reset_form' %}">Forgot Password?</a></h6>
				<div class="clearfix"></div>
				<input type="submit" value="Login" name="login">
		</form>
</div>
</div>


<script src="{% static 'adminstatic/js/bootstrap.js' %}"></script>
<script src="{% static 'adminstatic/js/jquery.dcjqaccordion.2.7.js' %}"></script>
<script src="{% static 'adminstatic/js/scripts.js' %}"></script>
<script src="{% static 'adminstatic/js/jquery.slimscroll.js' %}"></script>
<script src="{% static 'adminstatic/js/jquery.nicescroll.js' %}"></script>
<!--[if lte IE 8]><script language="javascript" type="text/javascript" src="{% static 'adminstatic/js/flot-chart/excanvas.min.js' %}"></script><![endif]-->
<script src="{% static 'adminstatic/js/jquery.scrollTo.js' %}"></script>
</body>
</html>

templates/clienttemplates/clientbase.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>Restro</title>

  <!-- Web-Fonts -->
  <link href="//fonts.googleapis.com/css?family=Spartan:400,500,600,700,900&display=swap" rel="stylesheet">
  <!-- //Web-Fonts -->

  <!-- Template CSS -->
  <link rel="stylesheet" href="{% static 'clientstatic/css/style-starter.css' %}">
  <link rel="stylesheet" href="{% static 'clientstatic/css/style.css' %}">
</head>

<body>
<!--header-->
<div class="w3l-top-header">
  <header id="site-header" class="fixed-top">
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-dark stroke">
        <a class="navbar-brand" href="/">
          <span class="fa fa-pie-chart"></span> Pizza pan
        </a>
        <!-- if logo is image enable this   
      <a class="navbar-brand" href="#/">
          <img src="image-path" alt="Your logo" title="Your logo" style="height:35px;" />
      </a> -->
        <button class="navbar-toggler  collapsed bg-gradient" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
          aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon fa icon-expand fa-bars"></span>
          <span class="navbar-toggler-icon fa icon-close fa-times"></span>
          </span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item @@index-active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item @@about-active">
              <a class="nav-link effect-3" href="{% url 'restroapp:aboutdetail' aboutdetail.id %}">About</a>
            </li>
            <li class="nav-item @@services-active">
              <a class="nav-link effect-3" href="/menu/">Menu</a>
            </li>
            <li class="nav-item @@services-active">
              <a class="nav-link effect-3" href="{% url 'restroapp:gallerylist' %}">Gallery</a>
            </li>
            <li class="nav-item @@contact-active">
              <a class="nav-link effect-3" href="/contact/">Contact</a>
            </li>
            <li class="px-4 fill-none">
              <a href="/order/" class="btn btn-style btn-secondary">Online Order</a>
              </li>
          </ul>
      
        </div>
      </nav>
    </div>
  </header>
</div>
<!--/header-->


{% block content %}



{% endblock %}






  <!-- footers 20 -->
  <section class="w3l-footers-20">
  	<div class="footers20">
  		<div class="container">
  			<div class="footers20-content">
  				<div class="d-grid grid-col-4 grids-content">

            {% for footer_contact in contact %}
            {% if forloop.counter == 1 %}
  					<div class="column">
  						<h4>Address</h4>
  						<p class="contact-para3">{{footer_contact.address}}</p>
  						<a>
  							<p class="contact-mail mt-2">{{footer_contact.email}}</p>
  						</a>
  					</div>
  					<div class="column">
  						<h4>Book a Table</h4>
  						<p>Make a call to Book Table</p>
  						<a>
  							<p class="contact-phone mt-2">{{footer_contact.phone}}</p>
  						</a>
  					</div>
  					<div class="column">
  						<h4>Opening hours</h4>
  						<p>{{footer_contact.open_day}}</p>
  						<p class="mt-2">{{footer_contact.open_time}}</p>
  					</div>
            {% endif %}
            {% endfor %}

  					<div class="column">
  						<h4>Thank you for visiting!!</h4>
  						<a>
  							<p><span class=" mr-2"></span>Hope you enjoy our service.</p>
  						</a>
  					</div>
  				</div>
  				<div class="d-grid grid-col-3 grids-content1 bottom-border">
  					<div class="columns copyright-grid">
  						<p class="copy-footer-29">© 2020 Restro. All rights reserved | Designed & Developed by <a
  								href="#">Rupak Ale</a></p>
  					</div>
  					<div class="columns text-right social-grid">
  						<ul class="social">
  							<li><a href="#url"><span class="fa fa-facebook" aria-hidden="true"></span></a></li>
  							<li><a href="#url"><span class="fa fa-instagram" aria-hidden="true"></span></a></li>
  							<li><a href="#url"><span class="fa fa-twitter" aria-hidden="true"></span></a></li>
  						</ul>
  					</div>
  				</div>
  			</div>
  		</div>
  	</div>
  </section>
  <!-- move top -->
  <button onclick="topFunction()" id="movetop" title="Go to top">
  	&#10548;
  </button>
  <script>
  	// When the user scrolls down 20px from the top of the document, show the button
  	window.onscroll = function () {
  		scrollFunction()
  	};

  	function scrollFunction() {
  		if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
  			document.getElementById("movetop").style.display = "block";
  		} else {
  			document.getElementById("movetop").style.display = "none";
  		}
  	}

  	// When the user clicks on the button, scroll to the top of the document
  	function topFunction() {
  		document.body.scrollTop = 0;
  		document.documentElement.scrollTop = 0;
  	}
  </script>
  <!-- /move top -->
  </section>

  <!-- jQuery and Bootstrap JS -->
  <script src="{% static 'clientstatic/js/jquery-3.3.1.min.js' %}"></script>

  <!-- libhtbox -->
  <script src="{% static 'clientstatic/js/lightbox-plus-jquery.min.js' %}"></script>


  <script src="{% static 'clientstatic/js/jquery.magnific-popup.min.js' %}"></script>

  <script src="{% static 'clientstatic/js/counter.js' %}"></script>
  <script>
  	$(document).ready(function () {
  		$('.popup-with-zoom-anim').magnificPopup({
  			type: 'inline',

  			fixedContentPos: false,
  			fixedBgPos: true,

  			overflowY: 'auto',

  			closeBtnInside: true,
  			preloader: false,

  			midClick: true,
  			removalDelay: 300,
  			mainClass: 'my-mfp-zoom-in'
  		});

  		$('.popup-with-move-anim').magnificPopup({
  			type: 'inline',

  			fixedContentPos: false,
  			fixedBgPos: true,

  			overflowY: 'auto',

  			closeBtnInside: true,
  			preloader: false,

  			midClick: true,
  			removalDelay: 300,
  			mainClass: 'my-mfp-slide-bottom'
  		});
  	});
  </script>

  <!-- testimonials owlcarousel -->
  <script src="{% static 'clientstatic/js/owl.carousel.js' %}"></script>
  <script>
  	$(document).ready(function () {
  		$('.owl-two').owlCarousel({
  			loop: true,
  			margin: 30,
  			nav: false,
  			responsiveClass: true,
  			autoplay: false,
  			autoplayTimeout: 5000,
  			autoplaySpeed: 1000,
  			autoplayHoverPause: false,
  			responsive: {
  				0: {
  					items: 1,
  					nav: false
  				},
  				480: {
  					items: 1,
  					nav: false
  				},
  				667: {
  					items: 1,
  					nav: false
  				},
  				1000: {
  					items: 1,
  					nav: false
  				}
  			}
  		})
  	})
  </script>
  <!-- //script for Testimonials-->

  <!-- script for food-->
  <script>
  	$(document).ready(function () {
  		$('.owl-carousel').owlCarousel({
  			loop: true,
  			margin: 0,
  			responsiveClass: true,
  			responsive: {
  				0: {
  					items: 1,
  					nav: true
  				},
  				480: {
  					items: 2,
  					nav: true,
  					margin: 20
  				},
  				769: {
  					items: 3,
  					nav: true,
  					margin: 20
  				},
  				1280: {
  					items: 4,
  					nav: true,
  					loop: true,
  					margin: 25
  				}
  			}
  		})
  	})
  </script>
  <!-- //script for food-->

  <!-- disable body scroll which navbar is in active -->
  <script>
  	$(function () {
  		$('.navbar-toggler').click(function () {
  			$('body').toggleClass('noscroll');
  		})
  	});
  </script>
  <!-- disable body scroll which navbar is in active -->
  <!--/MENU-JS-->
  <script>
  	$(window).on("scroll", function () {
  		var scroll = $(window).scrollTop();

  		if (scroll >= 80) {
  			$("#site-header").addClass("nav-fixed");
  		} else {
  			$("#site-header").removeClass("nav-fixed");
  		}
  	});

  	//Main navigation Active Class Add Remove
  	$(".navbar-toggler").on("click", function () {
  		$("header").toggleClass("active");
  	});
  	$(document).on("ready", function () {
  		if ($(window).width() > 991) {
  			$("header").removeClass("active");
  		}
  		$(window).on("resize", function () {
  			if ($(window).width() > 991) {
  				$("header").removeClass("active");
  			}
  		});
  	});
  </script>
  <!--//MENU-JS-->
  <script src="{% static 'clientstatic/js/bootstrap.min.js' %}"></script>

  </body>

  </html>

templates/clienttemplates/clienthome.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}
{% block content %}
<section class="w3l-banner" id="banner">
    <div class="new-block py-5">
        <div class="container">
            <div class="row middle-section">
                <div class="col-lg-7 section-width align-self">
                    <h5>{{bannerdetailview.slogon}}</h5>
                    <h2>{{bannerdetailview.some_text}}</h2>
                    <a href="/order/" class="btn btn-secondary btn-outline-style mt-md-5 mt-4"> 
                        <span class="fa fa-shopping-cart mr-2"></span> Order Online</a>
                </div>
                <div class="col-lg-5 history-info mt-lg-0 mt-5 pt-lg-0 pt-md-4 banner-image">
                    <img src="{{bannerdetailview.image.url}}" class="img-fluid" alt="image">
                    {% if bannerdetailview.price %}
                    <div class="cost">
                        <h5>Only</h5>
                        <h3>{{bannerdetailview.price}}</h3>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
</section>






<!-- iphone home block -->
<section class="w3l-about py-5 reason-background">
    <div class="container py-lg-5 py-md-4">
        <div class="row">
            <div class="col-lg-6">
                <h3>{{subabout.title}}</h3>
                <h5 class="mt-lg-3 mt-2">your satisfaction is our success</h5>
                <p class="mt-sm-4 mt-3 mb-sm-0 mb-2">{{subabout.detail|linebreaks}}</p>
                <a href="{% url 'restroapp:aboutdetail' aboutdetail.id %}" class="btn-style btn-primary btn mt-lg-5 mt-4">Know more about us</a>
            </div>


            <div class="col-lg-6 mt-lg-0 mt-5">
                <div class="row">

                    {% for reason in reason_to_choose %}
                    <div class="col-6 features-with-17-left1 " style="margin-bottom: 50px">
                        <a href="#url" class="icon"><img style="width: 4rem; height: 4rem; border-radius: 50%;" src="{{reason.image.url}}" alt="" /></a>
                        <h4><a href="#url">{{reason.title}}</a></h4>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>



<section class="w3l-portfolio-8 py-5 ">
    <div class="portfolio-main py-lg-5 py-md-4">
        <div class="container">
            <div class="title-content text-center">
                <h6 class="sub-title">Gallery</h6>
                <h3 class="title-big">Some Specials Captures</h3>
            </div>
            <div class="row galler-top mt-lg-5 mt-4">
                {% for gallery in gallerylist %}
                {% if forloop.counter <= 4 %}
                <div class="col-md-3 col-6 protfolio-item hover14 align-self">
                    <a href="{{gallery.image.url}}" data-lightbox="example-set"
                    data-title="{{gallery.title}}">
                            <figure>
                                <img src="{{gallery.image.url}}" alt="product" class="img-fluid radius-image gallery">
                            </figure>
                    </a>
                </div>
                

                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
                <div class="text-center">
                    <a href="{% url 'restroapp:gallerylist' %}" >see more</a>
                </div>
</section>
<section class="w3l-food" id="food">
    <div class="foods1 py-5 reason-background">
        <div class="container py-lg-5 py-md-4">
            <div class="title-content text-center">
                <h6 class="sub-title">Special Combo</h6>
                <h3 class="title-big">Our Special</h3>
            </div>
            <div class="foods1-content mt-lg-5 mt-4 mb-sm-0 mb-4">
                <div class="owl-carousel owl-theme text-center">

                    {% for special in ourspecial %}
                    <div class="item">
                        <div class="d-grid food-info">
                            <div class="column">
                                <h4 class="name-pos"><a>{{special.food_name}}</a></h4>
                                <p>{{special.combo}}</p>
                                <h5>{{special.price}}</h5>
                                <a href="/order/" class="btn-style btn-primary btn mt-4">Order Online</a>
                                <a href="#url"><img src="{{special.image.url}}" alt="" class="img-fluid radius-image mt-4"/></a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}


                </div>
            </div>
        </div>
    </div>
</section>

<!--/testimonials-->
	<section class="w3l-testimonials" id="testimonials">
		<div class="testimonials py-5">
			<div class="container py-lg-5 py-md-4">
				<div class="title-content text-center">
					<h6 class="sub-title">Testimonials</h6>
					<h3 class="title-big">What our Customer say</h3>
				</div>
				<div class="row mt-lg-5 mt-4">
					<div class="col-md-12 mx-auto">
						<div class="owl-two owl-carousel owl-theme">

                            {% for voice in clientvoice %}
							<div class="item">
								<div class="slider-info">
									<div class="message">
                                        <span class="fa fa-quote-left"></span>
										<h5>{{voice.voice}}</h5>
										<div class="name mt-4">
											<h4>{{voice.name}}</h4>
											<p>{{voice.post_company}}</p>
										</div>
									</div>
									<div class="img-circle">
										<img style=" height:20rem;" src="{{voice.image.url}}" class="img-fluid testimonial-img radius-image" alt="client">
									</div>
								</div>
							</div>

                            {% endfor %}


						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--//testimonials-->



	{% endblock %}

templates/clienttemplates/gallerylist.html
{% extends 'clienttemplates/clientbase.html' %}
{% block content %}




<!-- //Domain modal -->
<section class="w3l-breadcrumb">
    <div class="container">
        <ul class="breadcrumbs-custom-path">
            <li><a href="/">Home</a></li>
            <li class="active"><span class="fa fa-arrow-right mx-2" aria-hidden="true"></span> gallery</li>
        </ul>
    </div>
</section>


<!-- gallery section start here -->
<section class="w3l-portfolio-8 py-5 ">
    <div class="portfolio-main py-lg-5 py-md-4">
        <div class="container">
            <div class="title-content text-center">
                <h6 class="sub-title">Gallery</h6>
                <h3 class="title-big">Some Specials Captures</h3>
            </div>
            <div class="row galler-top mt-lg-5 mt-4">
                {% for gallery in gallerylistview %}
                <div class="col-md-3 col-6 protfolio-item hover14 align-self">
                    <a href="{{gallery.image.url}}" data-lightbox="example-set"
                    data-title="{{gallery.title}}">
                            <figure>
                                <img src="{{gallery.image.url}}" alt="product" class="img-fluid radius-image gallery">
                            </figure>
                    </a>
                </div>
                

                {% endfor %}
            </div>
        </div>
    </div>
                
</section>
<!-- gallery end -->




{% endblock %}