restroapp/urls.py
from django.urls import path, include
from .views import *
from restroapp import views


from django.contrib.auth import views as auth_views

app_name = 'restroapp'
urlpatterns = [



#client url
path('',ClientHomeView.as_view(), name = "clienthome"),



#about
path('about/<int:pk>/', AboutDetailView.as_view(), name = 'aboutdetail'),
path('about/<int:pk>/', SubAboutDetailView.as_view(), name = 'subabout'),


#message
path('contact/', MessageCreateView.as_view(), name = 'messagecreate'),


#contact
path('contact/', ContactListView.as_view(), name = 'contactlist'),


#team
path('about/<int:pk>/', TeamListView.as_view(), name = 'teamlist'),

#reason_to_choose
path('about/<int:pk>/', ReasonToChooseListView.as_view(), name = 'reason_to_choose'),

#client_voice
path('', ClientVoiceListView.as_view(), name = 'clientvoice'),


#order
path('order/', OrderCreateView.as_view(), name = 'order'),


#our_special
path('', OurSpecialListView.as_view(), name = 'ourspecial'),

#banner
path('', BannerDetailView.as_view(), name = 'bannerdetail'),


#gallery
path('gallery/list/', GalleryListView.as_view(), name = 'gallerylist'),
#food menu
path('menu/', Food_MenuListView.as_view(), name = 'menulist'),

#category
path('menu/', FoodCategory_ListView.as_view(), name = 'foodcategory'),



#login/logout
path('admin-login/',LoginView.as_view(),name="login"),
path('logout/', LogoutView.as_view(), name = 'logout'),



#admin urls start here

path('admin/home/', AdminHomeView.as_view(), name = 'adminhome'),

#Admin Profile
path('admin/profile/detail', AdminProfileDetailView.as_view(), name = 'adminprofiledetail'),


#contact 
path('admin/contact/', A_ContectListView.as_view(), name = 'a_contactlist'),
path('admin/contact/create/', A_ContactCreateView.as_view(), name = 'a_contactcreate'),
path('admin/contact/<int:pk>/update/', AdminContactUpdateView.as_view(), name = 'contactupdate'),


#message
path('message/list/', MessageListView.as_view(), name = 'messagelist'),
path('message/<int:pk>/delete/', MessageDeleteView.as_view(), name = 'messagedelete'),
path('message/<int:pk>/detail/', MessageDetailView.as_view(), name = 'messagedetailview'),



#About
path('admin/about/list/', A_AboutListView.as_view(), name = 'a_aboutlist'),
path('about/<int:pk>/update/', AboutUpdateView.as_view(), name = 'aboutupdateview'),
path('admin/subabout/list/', A_SubAboutListView.as_view(), name = 'a_subaboutlist'),
path('subabout/<int:pk>/update/', SubAboutUpdateView.as_view(), name = 'subaboutupdate'),

#team
path('admin/team/create/', A_TeamCreateView.as_view(), name = 'a_teamcreate'),
path('admin/team/list/', A_TeamListView.as_view(), name = 'a_teamlist'),
path('admin/team/<int:pk>/detail/', A_TeamDetailView.as_view(), name = 'a_teamdetail'),
path('admin/team/<int:pk>/delete/', A_TeamDeleteView.as_view(), name = 'a_teamdelete'),
path('admin/team/<int:pk>/update', A_TeamUpadateView.as_view(), name = 'a_teamupdate'),


#reason to choose us
path('admin/reason/create/', A_ReasonCreateView.as_view(), name = 'a_reasoncreate'),
path('admin/reason/list/', A_ReasonListView.as_view(), name = 'a_reasonlist'),
path('admin/reason/<int:pk>/detail/', A_ReasonDetailView.as_view(), name = 'a_reasondetail'),
path('admin/reason/<int:pk>/delete/', A_ReasonDeleteView.as_view(), name = 'a_reasondelete'),
path('admin/reason/<int:pk>/update/', A_ReasonUpdateView.as_view(), name = 'a_reasonupdate'),



#our special
path('admin/special/create/', A_SpecialCreateView.as_view(), name = 'a_specialcreate'),
path('admin/special/list/', A_SpecialListView.as_view(), name = 'a_speciallist'),
path('admin/special/<int:pk>/detail/', A_SpecialDetailView.as_view(), name = 'a_specialdetail'),
path('admin/special/<int:pk>/delete/', A_SpecialDeleteView.as_view(), name = 'a_specialdelete'),
path('admin/special/<int:pk>/update/', A_SpecialUpdateView.as_view(), name = 'a_specialupdate'),



#clientVoice urls
path('admin/voice/create/', A_VoiceCreateView.as_view(), name = 'a_clientvoicecreate'),
path('admin/voice/list/', A_VoiceListView.as_view(), name = 'a_clientvoicelist'),
path('admin/voice/<int:pk>/detail/', A_VoiceDetailView.as_view(), name = 'a_clientvoicedetail'),
path('admin/voice/<int:pk>/delete/', A_VoiceDeleteView.as_view(), name = 'a_clientvoicedelete'),
path('admin/voice/<int:pk>/update/', A_VoiceUpdateView.as_view(), name = 'a_clientvoiceupdate'), 



#online order urls
path('admin/order/list/', A_OrderListView.as_view(), name = 'a_orderlist'),
path('admin/order/<int:pk>/detail/', A_OrderDetailView.as_view(), name = 'a_orderdetail'),
path('admin/order/<int:pk>/delete/', A_OrderDeleteView.as_view(), name = 'a_orderdelete'),


#banner urls
path('admin/banner/list/', A_BannerListView.as_view(), name = 'a_bannerlist'),
path('admin/banner/<int:pk>/update/', A_BannerUpdateView.as_view(), name = 'a_bannerupdate'),


#gallery urls
path('admin/gallery/create/', A_GalleryCreateView.as_view(), name = 'a_gallerycreate'),
path('admin/gallery/list/', A_GalleryListView.as_view(), name = 'a_gallerylist'),
path('admin/gallery/<int:pk>/delete/', A_GalleryDeleteView.as_view(), name = 'a_gallerydelete'),
path('admin/gallery/<int:pk>/update/', A_GalleryUpdateView.as_view(), name = 'a_galleryupdate'),


#FoodCategory urls
path('admin/food-category/create/', FoodCategoryCreateView.as_view(), name = 'foodcategorycreate'),
path('admin/food-category/<int:pk>/delete/',FoodCategoryDeleteView.as_view(), name = 'foodcategorydelete'),
path('admin/food-category/list/', FoodCategoryListView.as_view(), name = 'foodcategorylist'),


#FoodMenu urls
path('admin/food-menu/create/', FoodMenuCreateView.as_view(), name = 'foodmenucreate'),
path('admin/food-menu/<int:pk>/update', FoodMenuUpdateView.as_view(), name = 'foodmenuupdate'),
path('admin/food-menu/list/', FoodMenuListView.as_view(), name = 'foodmenulist'),
path('admin/food-menu/<int:pk>/', FoodMenuDetailView.as_view(), name = 'foodmenudetail'),
path('admin/food-menu/<int:pk>/delete/', FoodMenuDeleteView.as_view(), name = 'foodmenudelete'),


#admin settings
path('admin/settings',A_SettingsView.as_view(), name = 'a_settings'),


#admin registration
path('admin/registration/',A_RegistrationView.as_view(), name = 'a_registration'),
path('activate/<uidb64>/<token>/',views.activate, name='activate'),

#username check
path('username-check/',UsernameCheckView.as_view(), name = 'username_check'),



#user authentication
path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(template_name='admintemplates/change-password.html',
        	success_url = '/change-password-done/'),
        name = 'password_change'
    ),
path(
		'change-password-done/',
		auth_views.PasswordChangeDoneView.as_view(
			template_name = 'admintemplates/password_change_done.html'),
		name = 'password_change_done' 
	),


path('password-reset/',auth_views.PasswordResetView.as_view(
    template_name = 'admintemplates/password_reset_form.html',
    subject_template_name='admintemplates/password_reset_subject.txt',
    email_template_name='admintemplates/password_reset_email.html',
    success_url = '/password_reset/done/'
 ), name = 'password_reset_form'),


path('password_reset/done/',
     auth_views.PasswordResetDoneView.as_view(
         template_name='admintemplates/password_reset_done.html'
     ),
     name='password_reset_done'),
path('password-reset-confirm/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(
         template_name='admintemplates/password_reset_confirm.html',
         success_url = '/reset/done/'
     ),
     name='password_reset_confirm'),
path('reset/done/',
     auth_views.PasswordResetCompleteView.as_view(
         template_name='admintemplates/password_reset_complete.html'
     ),
     name='password_reset_complete'),
]

restroproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path,include


from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('restroapp.urls')),
    path('',include("django.contrib.auth.urls"))
    

]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/admintemplates/a_aboutlist.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}

<style>
  .fa {
    font-size: 20px;
  }
</style>

<!--main content start-->
<section id="main-content">
  <section class="wrapper">
    <div class="table-agile-info">
        <a href="{% url 'restroapp:adminhome' %}" class="fa fa-long-arrow-left" area-hidden = 'true'>back</a>

      {% for about in a_aboutlistview %}
      {% if forloop.counter == 1%}
      <div class="panel panel-default">
        <div class="row mx-auto">
          <div class="col-md-8 col-sm-8 col-lg-8">
            <h3 class="form-group">Title: {{about.title}}</h3>
            <label>Detail:</label>
            <p class="form-group">{{about.detail}}</p>

           </div> 
        </div>
      </div>
      <div>
        
        <a href="{% url 'restroapp:aboutupdateview' about.id %}"><button type="button" class="btn btn-primary" >Edit About</button>
          {% endif %}
      {% endfor %}

      </div>
    </div>
</section>


{% endblock %}

templates/admintemplates/a_bannerupdate.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}


<!--main content start-->
<section id="main-content">
	<section class="wrapper">
	<div class="form-w3layouts">
        <a href="{% url 'restroapp:adminhome' %}">cancel</a>
        <!-- page start-->
        <!-- page start-->
        <div class="row">
            <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            Edit Banner
                        </header>
                        <div class="panel-body">
                            <div class="position-center">
                                <form role="form" method="POST" enctype="multipart/form-data">
                                	{% csrf_token %}
                                <div class="form-group">
                                    <label >Slogon</label>
                                    {{form.slogon}}
                                   
                                </div>
                                <div class="form-group">
                                    <label>Some text</label>
                                    {{form.some_text}}
                                   
                                </div>
                                <div class="form-group">
                                    <label >Image</label>
                                    {{form.image}}
                                   
                                </div>
                                <div class="form-group">
                                    <label>Price</label>
                                    {{form.price}}
                                   
                                </div>
                               
                                <button type="submit" class="btn btn-info">Done</button>
                            </form>
                            </div>

                        </div>
                    </section>

            </div>
        </div>
    </div>





        <!-- page end-->
</section>

{% endblock %}

templates/admintemplates/a_contactlist.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}

<style>
  .fa {
    font-size: 20px;
  }
</style>

<!--main content start-->
<section id="main-content">
  <section class="wrapper">
    <div class="table-agile-info">
        <a href="{% url 'restroapp:adminhome' %}" class="fa fa-long-arrow-left" area-hidden = 'true'>back</a>

      {% for contact in a_contactlistview %}
      {% if forloop.counter == 1%}
      <div class="panel panel-default">
        <div class="row mx-auto">
          <div class="col-md-8 col-sm-8 col-lg-8">
            <h3 class="form-group">Phone: {{contact.phone}}</h3>
            <p class="form-group">Email: {{contact.email}}</p>
            <p class="form-group">Address: {{contact.address}}</p>
            <p class="form-group">Open Days: {{contact.open_day}}</p>
            <p class="form-group">Open Hours: {{contact.open_time}}</p>
           </div> 
        </div>
      </div>
      <div>
        
        <a href="{% url 'restroapp:contactupdate' contact.id %}"><button type="button" class="btn btn-primary" >Edit Contact</button>
          {% endif %}
      {% endfor %}

      </div>
    </div>
</section>


{% endblock %}

templates/admintemplates/a_gallerylist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content %}


<!--main content start-->
<section id="main-content">
	<section class="wrapper">
		<!-- gallery -->
		<!-- gallery -->
		<div style="margin-bottom: 5px;">
			<a href="{% url 'restroapp:a_gallerycreate'%}" type="button" class="btn btn-primary">Add Photo</a>
		</div>
	<div class="gallery">
		<h2 class="w3ls_head">Gallery</h2>
		<div class="gallery-grids">
				<div class="gallery-top-grids">

					{% for gallery in a_gallerylistview %}
					<div class="col-sm-4 gallery-grids-left">
						<div class="gallery-grid">
							<p class="example-image-link" href="{{gallery.image.url}}" data-lightbox="example-set" data-title="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vitae cursus ligula">
								<img class="gallery-img"s src="{{gallery.image.url}}" alt="" />
								<div class="captn">
									<h4>Restro</h4>
									<p>{{gallery.title}}</p>
									<p><a style="color: white;" href="{% url 'restroapp:a_galleryupdate' gallery.id %}">Edit</a> / <a style="color: white;" href="{% url 'restroapp:a_gallerydelete'  gallery.id %}">Delete</a></p>
								</div>
							</p>
						</div>
					</div>
					{% endfor %}
					<div class="clearfix"> </div>
				</div>
				<div class="clearfix"> </div>
				<script src="{% static 'adminstatic/js/lightbox-plus-jquery.min.js' %}"> </script>
		
	</div>
	</div>
	<!-- //gallery -->

</section>


{% endblock %}

templates/admintemplates/a_specialdelete.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}

<style>
  .fa {
    font-size:20px;
  }

.button {
    margin: 1.2rem;
    text-align: center;
    /*padding:0rem 2rem;*/
    font-size: 1.3rem;

  }
</style>

<!--main content start-->
<section id="main-content">
  <section class="wrapper">
    <div class="table-agile-info">

    <a href="{% url 'restroapp:a_speciallist' %}" class="fa fa-long-arrow-left">back</a>
     <div class="panel panel-default">
        <div class="p-3">
          <form method="POST">
            {% csrf_token %}
            <div>
              <h4 class="text-danger margin" style="text-align: center ; padding: 20px 0 10px ;"> Are you sure to delete?</h4>


              <div class="center">
                <button class="btn btn-danger button" type="submit">Yes</button>
                <a href="{% url 'restroapp:a_speciallist' %}" type="button" class="btn btn-success button">No</a>
              </div>
            </div>
          </form>
        </div>

      </div>
</div>
</section>


{% endblock %}

templates/admintemplates/a_voicedetail.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}

<style>
  .fa {
    font-size: 20px;
  }
</style>

<!--main content start-->
<section id="main-content">
  <section class="wrapper">
    <div class="table-agile-info">
        <a href="{% url 'restroapp:a_clientvoicelist' %}" class="fa fa-long-arrow-left" area-hidden = 'true'>back</a>
      <div class="panel panel-default">

        <div class="row mx-auto">
          <div class="col-md-8 col-sm-8 col-lg-8">
            <h3 class="form-group">Name: {{a_voicedetailview.name}}</h3>
            <img style="width: 15rem; height: 15rem;" src="{{a_voicedetailview.image.url}}"><br>
            <label><b>Voice:</b></label>
            <p class="form-group">{{a_voicedetailview.voice}}</p>
            <p class="form-group">Post & Company: {{a_voicedetailview.post_company}}</p>

          </div> 
           


        </div>
      </div>
      <div>
        <a href="{% url 'restroapp:a_clientvoicedelete' a_voicedetailview.id %}"><button type="button" class="btn btn-primary" >Delete</button>
        <a href="{% url 'restroapp:a_clientvoiceupdate' a_voicedetailview.id %}"><button type="button" class="btn btn-primary" >Edit</button>

      </div>
    </div>
</section>


{% endblock %}

templates/admintemplates/a_voicelist.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}

<!--main content start-->
<section id="main-content">
	<section class="wrapper">
		<div class="table-agile-info">
      <div style="margin-bottom: 5px;">
      <a href="{% url 'restroapp:a_clientvoicecreate' %}" type="button" class="btn btn-primary">Add Customer Voice</a>
    </div>
 <div class="panel panel-default">
    <div class="panel-heading">
     Customer Voices
    </div>
    <div>
      <table class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'>
 		<thead>
          <tr>
            <th>S.N</th>
            <th>Name</th>
            <th>Post & Company</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
        	{% for voice in a_voicelistview %}
          <tr data-expanded="true">
            <td>{{forloop.counter}}</td>
            <td><a href="{% url 'restroapp:a_clientvoicedetail' voice.id %}">{{voice.name}}</a></td>
            <td>{{voice.post_company}}</td>
            
            <td>
              <a href="{% url 'restroapp:a_clientvoicedelete' voice.id %}"><button type="button" class="btn btn-primary" >Delete</button>
            	<a href="{% url 'restroapp:a_clientvoiceupdate' voice.id %}"><button type="button" class="btn btn-primary" >Edit</button>
				</a>
			</td>
          </tr>
          {% endfor %}



        </tbody>
      </table>
    </div>
  </div>
</div>
</section>




{% endblock %}

templates/admintemplates/aboutupdate.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}


<!--main content start-->
<section id="main-content">
	<section class="wrapper">
	<div class="form-w3layouts">
        <!-- page start-->
        <!-- page start-->
        <div class="row">
            <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            Edit Your About
                        </header>
                        <div class="panel-body">
                            <div class="position-center">
                                <form role="form" method="POST" >
                                	{% csrf_token %}
                                <div class="form-group">
                                    <label >Title</label>
                                    {{form.title}}
                                   
                                </div>
                                <div class="form-group">
                                    <label >Detail</label>
                                    {{form.detail}}
                                   
                                </div>
                               
                                <button type="submit" class="btn btn-info">Done</button>
                            </form>
                            </div>

                        </div>
                    </section>

            </div>
        </div>
    </div>





        <!-- page end-->
</section>
</section>

{% endblock %}

templates/admintemplates/foodcategorycreate.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}


<!--main content start-->
<section id="main-content">
	<section class="wrapper">
	<div class="form-w3layouts">
        <a href="{% url 'restroapp:adminhome' %}">cancel</a>
        <!-- page start-->
        <!-- page start-->
        <div class="row">
            <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            Add/Edit Food Category
                        </header>
                        <div class="panel-body">
                            <div class="position-center">
                                <form role="form" method="POST" >
                                	{% csrf_token %}
                                <div class="form-group">
                                    <label >Food Type</label>
                                    {{form.food_type}}
                                   
                                </div>
                               
                                
                               
                                <button type="submit" class="btn btn-info">Done</button>
                            </form>
                            </div>

                        </div>
                    </section>

            </div>
        </div>
    </div>





        <!-- page end-->
</section>

{% endblock %}

templates/admintemplates/foodmenudelete.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}

<style>
  .fa {
    font-size:20px;
  }

.button {
    margin: 1.2rem;
    text-align: center;
    /*padding:0rem 2rem;*/
    font-size: 1.3rem;

  }
</style>

<!--main content start-->
<section id="main-content">
  <section class="wrapper">
    <div class="table-agile-info">

    <a href="{% url 'restroapp:foodmenulist' %}" class="fa fa-long-arrow-left">back</a>
     <div class="panel panel-default">
        <div class="p-3">
          <form method="POST">
            {% csrf_token %}
            <div>
              <h4 class="text-danger margin" style="text-align: center ; padding: 20px 0 10px ;"> Are you sure to delete?</h4>


              <div class="center">
                <button class="btn btn-danger button" type="submit">Yes</button>
                <a href="{% url 'restroapp:foodmenulist' %}" type="button" class="btn btn-success button">No</a>
              </div>
            </div>
          </form>
        </div>

      </div>
</div>
</section>


{% endblock %}

templates/admintemplates/messagelist.html
{% extends 'admintemplates/adminbase.html' %}

{% block content %}

<!--main content start-->
<section id="main-content">
	<section class="wrapper">
		<div class="table-agile-info">
 <div class="panel panel-default">
    <div class="panel-heading">
     Your Messages
    </div>
    <div>
      <table class="table" ui-jq="footable" ui-options='{
        "paging": {
          "enabled": true
        },
        "filtering": {
          "enabled": true
        },
        "sorting": {
          "enabled": true
        }}'>
 		<thead>
          <tr>
            <th>S.N</th>
            <th>Name</th>
            <th>Send At</th>
           
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
        	{% for admin_message in message %}
          <tr data-expanded="true">
            <td>{{forloop.counter}}</td>
            <td><a href="{% url 'restroapp:messagedetailview' admin_message.id %}">{{admin_message.name}}</a></td>
            <td>{{admin_message.created_at|timesince}} ago</td>
            
            <td>
            	<a href="{% url 'restroapp:messagedelete' admin_message.id%}"><button type="button" class="btn btn-primary" >Delete</button>
				</a>
			</td>
          </tr>
          {% endfor %}



        </tbody>
      </table>
    </div>
  </div>
</div>
</section>




{% endblock %}

templates/admintemplates/password_reset_confirm.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<head>
<title>Restro|Admin-Login</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Visitors Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- bootstrap-css -->
<link rel="stylesheet" href="{% static 'adminstatic/css/bootstrap.min.css' %}" >
<!-- //bootstrap-css -->
<!-- Custom CSS -->
<link href="{% static 'adminstatic/css/style.css' %}" rel='stylesheet' type='text/css' />
<link href="{% static 'adminstatic/css/style-responsive.css' %}" rel="stylesheet"/>
<!-- font CSS -->
<link href='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
<!-- font-awesome icons -->
<link rel="stylesheet" href="{% static 'adminstatic/css/font.css' %}" type="text/css"/>
<link href="{% static 'adminstatic/css/font-awesome.css' %}" rel="stylesheet"> 
<!-- //font-awesome icons -->
<script src="{% static 'adminstatic/js/jquery2.0.3.min.js' %}"></script>
</head>
<body>
	<div class="log-w3">
		<div class="w3layouts-main">
			<h2>Reset Password</h2>
			<h3>Enter your new password</h3>
			<form class="form" action="" method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				{{ form|crispy }}
				<button type="submit" class="btn btn-primary btn-lg btn-block"><i class="icon-lock4"></i> Change Password</button>
			</form> 
		</div>
	</div>
<script src="{% static 'adminstatic/js/bootstrap.js' %}"></script>
<script src="{% static 'adminstatic/js/jquery.dcjqaccordion.2.7.js' %}"></script>
<script src="{% static 'adminstatic/js/scripts.js' %}"></script>
<script src="{% static 'adminstatic/js/jquery.slimscroll.js' %}"></script>
<script src="{% static 'adminstatic/js/jquery.nicescroll.js' %}"></script>
<!--[if lte IE 8]><script language="javascript" type="text/javascript" src="{% static 'adminstatic/js/flot-chart/excanvas.min.js' %}"></script><![endif]-->
<script src="{% static 'adminstatic/js/jquery.scrollTo.js' %}"></script>
</body>
</html>